project:
  type: website
  output-dir: docs

website:
  title: "compmemlearn"
  navbar:
    type: dark
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Datasets"
        contents:
          - library/datasets/Murdock1962.ipynb
          - library/datasets/MurdockOkada1970.ipynb
          - library/datasets/Lohnas2014.ipynb
          - library/datasets/HowaKaha05.ipynb
          - library/datasets/Data_Simulation.ipynb
          - library/datasets/ClairExpt6.ipynb
          - library/datasets/PEERS.ipynb
      - section: "Models"
        contents:
          - library/models/Classic_CMR.ipynb
          - library/models/Instance_CMR.ipynb
          - library/models/Noisy_CMR.ipynb
          - library/models/Trace_Reinstatement_CMR.ipynb
      - section: "Data Analysis"
        contents:
          - library/analyses/Serial_Position_Effect.ipynb
          - library/analyses/Probability_of_First_Recall.ipynb
          - library/analyses/Lag_Contiguity_Effect.ipynb
          - library/analyses/Conditional_Stop_Probability.ipynb
          - library/analyses/Alternative_Contiguity.ipynb
          - library/analyses/Recall_Probability_by_Spacing.ipynb
          - library/analyses/Serial_Position_Effect_in_Repetition_Datasets.ipynb
          - library/analyses/Probability_of_First_Recall_in_Repetition_Data.ipynb
          - library/analyses/Lag_Contiguity_Effect_with_Repetition_Data.ipynb
      - section: "Model Analysis"
        contents:
          - library/model_analysis/Data_Likelihood_Under_Model.ipynb
          - library/model_analysis/Contiguity_Tracing.ipynb
          - library/model_analysis/Model_Characterization.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



