project:
  type: book

book:
  title: "An Instance-Based Account of Context Maintenance and Retrieval"
  author: "Jordan Gunn"
  date: "10/31/2021"
  chapters:
    - index.md
    - 02_Introduction.md
    - 04_Classic_CMR.md
    - 05_InstanceCMR.md
    - 06_Methods.md
    - 07_Baseline_Comparison.md
    - 08_Variable_List_Lengths.md
    - 09_Item_Repetitions_Sims.md
    - 09_Item_Repetitions_Lohnas.md
    - 10_Discussion.md
    - references.md

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    header-includes: |
      \usepackage{arxiv}
    toc: false
    documentclass: article
  epub:
    cover-image: cover.png