project:
  type: book

book:
  title: "RepFR"
  lang: "en"
  execute: false
  chapters:
    - index.ipynb
    - Data_Overview.ipynb
    - Likelihood_Based_Fitting.ipynb
    - Likelihood_Based_Fitting_Without_Delay_Drift.ipynb
    - Likelihood_Based_Fitting_Without_First_Recall.ipynb
    - Likelihood_Based_Fitting_CMRDE.ipynb
    - Statistic_Based_Fitting_to_Repetition_Effects.ipynb
    - ClaireExpt6.ipynb

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
  pdf:
    author: 
      - |
        | Jordan B. Gunn
        | Cognition and Cognitive Neuroscience Program
        | Vanderbilt University
        | Nashville, TN 37235
        | \texttt{jordan.gunn@vanderbilt.edu}
    header-includes: |
      \usepackage{setspace}
      \onehalfspacing
      %\doublespacing
      \usepackage{arxiv}
    toc: false
    keep-tex: true
    echo: false
    output: false
    documentclass: article
    #classoption:  12pt