project:
  type: book

book:
  title: "An Instance-Based Account of Context Maintenance and Retrieval"
  author: "Jordan Gunn"
  date: "11/16/2021"
  lang: "en"
  chapters:
    - index.ipynb
    - 00_Introduction.ipynb
    - 01_Classic_CMR.ipynb
    - 02_Instance_CMR.ipynb
    - 03_Methods.ipynb
    - 04_Baseline_Comparison.ipynb
    - 05_Variable_List_Lengths.ipynb
    - 06_Item_Repetitions_Sims.ipynb
    - 06_Item_Repetitions_Lohnas.ipynb
    - 07_Discussion.ipynb
    - references.md

bibliography: references.bib

format:
  html:
    theme: cosmo
    echo: false
    code-fold: true
  pdf:
    header-includes: |
      \usepackage{arxiv}
    toc: false
    keep-tex: true
    documentclass: article