# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"prepare_murdock1962_data": "00_Preparing_Free_Recall_Data.ipynb",
         "prepare_murdock1970_data": "00_Preparing_Free_Recall_Data.ipynb",
         "prepare_lohnas2014_data": "00_Preparing_Free_Recall_Data.ipynb",
         "simulate_data": "00_Preparing_Free_Recall_Data.ipynb"}

modules = ["datasets.py"]

doc_url = "https://githubpsyche.github.io/compmemlearn/"

git_url = "https://github.com/githubpsyche/compmemlearn/tree/main/"

def custom_doc_links(name): return None
