# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"plot_spc": "Benchmark_Recall_Phenomena.ipynb",
         "fast_spc": "Benchmark_Recall_Phenomena.ipynb",
         "plot_lag_crp": "Benchmark_Recall_Phenomena.ipynb",
         "fast_crp": "Benchmark_Recall_Phenomena.ipynb",
         "plot_pfr": "Benchmark_Recall_Phenomena.ipynb",
         "fast_pfr": "Benchmark_Recall_Phenomena.ipynb",
         "randomize_dataset": "Measuring_Repetition_Effects.ipynb",
         "sim_recall_probability_by_lag": "Measuring_Repetition_Effects.ipynb",
         "indices_of_repeated_items": "Measuring_Repetition_Effects.ipynb",
         "alternative_contiguity_test": "Measuring_Repetition_Effects.ipynb",
         "alternative_contiguity_control": "Measuring_Repetition_Effects.ipynb",
         "sim_alternative_contiguity_test": "Measuring_Repetition_Effects.ipynb",
         "recall_probability_by_lag": "Recall_Probability_by_Spacing.ipynb",
         "simulate_df": "Data_Simulation.ipynb",
         "simulate_data": "Data_Simulation.ipynb",
         "simulate_array": "Data_Simulation.ipynb",
         "prepare_murdock1962_data": "Preparing_Free_Recall_Data.ipynb",
         "prepare_murdock1970_data": "Preparing_Free_Recall_Data.ipynb",
         "prepare_lohnas2014_data": "Preparing_Free_Recall_Data.ipynb",
         "prepare_howakaha05_data": "Preparing_Free_Recall_Data.ipynb",
         "murdock_data_likelihood": "Fitting_by_Likelihood.ipynb",
         "murdock_objective_function": "Fitting_by_Likelihood.ipynb",
         "lohnas_data_likelihood": "Fitting_by_Likelihood.ipynb",
         "lohnas_objective_function": "Fitting_by_Likelihood.ipynb",
         "apply_and_concatenate": "Fitting_by_Likelihood.ipynb",
         "encoding_states": "Model_Visualization.ipynb",
         "plot_states": "Model_Visualization.ipynb",
         "encoding_visualizations": "Model_Visualization.ipynb",
         "latent_mfc_mcf": "Model_Visualization.ipynb",
         "retrieval_states": "Model_Visualization.ipynb",
         "outcome_probs_at_index": "Model_Visualization.ipynb",
         "retrieval_visualizations": "Model_Visualization.ipynb",
         "temporal_organization_analyses": "Model_Visualization.ipynb",
         "cmr_spec": "Classic_CMR.ipynb",
         "Classic_CMR": "Classic_CMR.ipynb",
         "icmr_spec": "Instance_CMR.ipynb",
         "Instance_CMR": "Instance_CMR.ipynb"}

modules = ["analyses.py",
           "datasets.py",
           "fitting.py",
           "model_analysis.py",
           "models.py"]

doc_url = "https://githubpsyche.github.io/compmemlearn/"

git_url = "https://github.com/githubpsyche/compmemlearn/tree/main/"

def custom_doc_links(name): return None
