# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"cmr_spec": "Classic_CMR.ipynb",
         "Classic_CMR": "Classic_CMR.ipynb",
         "murdock_data_likelihood": "Fitting_by_Likelihood.ipynb",
         "murdock_objective_function": "Fitting_by_Likelihood.ipynb",
         "apply_and_concatenate": "Fitting_by_Likelihood.ipynb",
         "icmr_spec": "Instance_CMR.ipynb",
         "Instance_CMR": "Instance_CMR.ipynb",
         "randomize_dataset": "Measuring_Repetition_Effects.ipynb",
         "sim_recall_probability_by_lag": "Measuring_Repetition_Effects.ipynb",
         "indices_of_repeated_items": "Measuring_Repetition_Effects.ipynb",
         "alternative_contiguity_test": "Measuring_Repetition_Effects.ipynb",
         "alternative_contiguity_control": "Measuring_Repetition_Effects.ipynb",
         "sim_alternative_contiguity_test": "Measuring_Repetition_Effects.ipynb",
         "extended_apply_and_concatenate": "CMR_Configurations_Across_Lohnas2015_Conditions.ipynb",
         "familiarity_weighting": "Differential_Encoding_Mechanism.ipynb",
         "aic": "DE_Fitting_Benchmarks.ipynb",
         "encoding_states": "Model_Visualization.ipynb",
         "plot_states": "Model_Visualization.ipynb",
         "encoding_visualizations": "Model_Visualization.ipynb",
         "latent_mfc_mcf": "Model_Visualization.ipynb",
         "retrieval_states": "Model_Visualization.ipynb",
         "outcome_probs_at_index": "Model_Visualization.ipynb",
         "retrieval_visualizations": "Model_Visualization.ipynb",
         "temporal_organization_analyses": "Model_Visualization.ipynb",
         "lohnas_data_likelihood": "09_Comparing_Instance_and_Classic_CMR_Lohnas2015.ipynb",
         "lohnas_objective_function": "09_Comparing_Instance_and_Classic_CMR_Lohnas2015.ipynb",
         "prepare_murdock1962_data": "Preparing_Free_Recall_Data.ipynb",
         "prepare_murdock1970_data": "Preparing_Free_Recall_Data.ipynb",
         "prepare_lohnas2014_data": "Preparing_Free_Recall_Data.ipynb",
         "prepare_howakaha05_data": "Preparing_Free_Recall_Data.ipynb",
         "simulate_data": "Preparing_Free_Recall_Data.ipynb",
         "recall_probability_by_lag": "Recall_Probability_by_Spacing.ipynb",
         "serial_position_curve": "Serial_Position_Curve.ipynb"}

modules = ["models.py",
           "fitting.py",
           "analyses.py",
           "model_fitting.py",
           "familiarity.py",
           "model_analysis.py",
           "datasets.py"]

doc_url = "https://githubpsyche.github.io/compmemlearn/"

git_url = "https://github.com/githubpsyche/compmemlearn/tree/main/"

def custom_doc_links(name): return None
