# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/00_Preparing_Free_Recall_Data.ipynb (unless otherwise specified).

__all__ = ['say_hello']

# Cell
def say_hello(to):
    """
    >>> say_hello('world')
    Hello world!
    """
    return "Hello {}!".format(to)