# AUTOGENERATED! DO NOT EDIT! File to edit: library/03_CMR_DE/Three_Param_Differential_Encoding_Mechanism.ipynb (unless otherwise specified).

__all__ = ['familiarity_weighting', 'familiarity_weighting']

# Cell

from numba import njit
import numpy as np

@njit
def familiarity_weighting(familiarity_scale, similarity):
    return np.power(1-similarity, familiarity_scale)

# Cell

from numba import njit
import numpy as np

@njit
def familiarity_weighting(familiarity_scale, similarity):
    return 1 if ((1-similarity) == 0) else familiarity_scale