# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/01_Repetition_CMR/CMR_Configurations_Across_Murdock1962_Conditions.ipynb (unless otherwise specified).

__all__ = ['extended_apply_and_concatenate', 'extended_apply_and_concatenate']

# Cell

def extended_apply_and_concatenate(function, dfs, contrast_name='contrast', labels='AB'):
    """
    Concatenates the results of a function applied to passed dataframes and creates a new column identifying the contrast.
    """
    return pd.concat([function(df) for df in dfs], keys=labels, names=[contrast_name]).reset_index()

# Cell

def extended_apply_and_concatenate(function, dfs, contrast_name='contrast', labels='AB'):
    """
    Concatenates the results of a function applied to passed dataframes and creates a new column identifying the contrast.
    """
    return pd.concat([function(df) for df in dfs], keys=labels, names=[contrast_name]).reset_index()